---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn-tls
  namespace: longhorn-system
spec:
  secretName: longhorn-tls-secret
  issuerRef:
    name: longhorn.foobar.de
    kind: ClusterIssuer
  commonName: longhorn.foobar.de
