---
apiVersion: v1
kind: ConfigMap
metadata:
  name: node-exporter-web-config
  namespace: monitoring
data:
  web-config.yaml: |
    tls_server_config:
      cert_file: /etc/node-exporter/tls/tls.crt
      key_file: /etc/node-exporter/tls/tls.key
    basic_auth_users:
      promscraper: $2b$12$/JU070BCPeejiR70jEzQj.JiUH82diCHJ6Yyf5XoLTfHFOwLPGkK2