---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: node-exporter
    name: node-exporter
    component: exporter
  name: node-exporter
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: node-exporter
      name: node-exporter
      component: exporter
  template:
    metadata:
      labels:
        app: node-exporter
        name: node-exporter
        component: exporter
    spec:
      containers:
        - name: node-exporter
          image: prom/node-exporter
          args:
            - "--web.config.file=/etc/node-exporter/web-config/web-config.yaml"
            - "--path.sysfs=/host/sys"
            - "--path.rootfs=/host/root"
            - "--no-collector.wifi"
            - "--no-collector.hwmon"
            - "--collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/pods/.+)($|/)"
            - "--collector.netclass.ignored-devices=^(veth.*)$"
          ports:
            - containerPort: 9100
              protocol: TCP
          volumeMounts:
            - name: web-config
              mountPath: /etc/node-exporter/web-config
              readOnly: true
            - name: tls-certs
              mountPath: /etc/node-exporter/tls
              readOnly: true
            - mountPath: /host/sys
              mountPropagation: HostToContainer
              name: sys
              readOnly: true
            - mountPath: /host/root
              mountPropagation: HostToContainer
              name: root
              readOnly: true
      volumes:
        - name: web-config
          configMap:
            name: node-exporter-web-config
            defaultMode: 420
        - name: tls-certs
          secret:
            secretName: node-exporter-tls-secret
        - hostPath:
            path: /sys
          name: sys
        - hostPath:
            path: /
          name: root
