---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-node-discovery
rules:
  - apiGroups: [""]
    resources:
      - nodes
    verbs:
      - "get"
      - "watch"
      - "list"
