---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-node-discovery
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-node-discovery
subjects:
  - kind: ServiceAccount
    name: prometheus-node-discovery
    namespace: monitoring
