---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-server-tls
  namespace: monitoring
spec:
  secretName: prometheus-server-tls-secret
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  commonName: prometheus.foobar.de
