---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-config
  namespace: monitoring
data:
  prometheus.yml: |
    global: 
      scrape_interval: 30s
      scrape_timeout: 10s
    
    scrape_configs:
      - job_name: "prometheus"
        scheme: https
        tls_config:
          insecure_skip_verify: true
        static_configs:
          - targets: ["localhost:9090"]
      
      - job_name: 'node-exporter'
        scheme: https
        tls_config:
          insecure_skip_verify: true
        basic_auth:
          username: promscraper
          password: RZWYCLDYk81}EQlI
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - source_labels: [__meta_kubernetes_node_address_Hostname]
            action: replace
            target_label: __address__
            regex: (.*)
            replacement: ${1}:30100
          - source_labels: [__meta_kubernetes_node_name]
            action: replace
            target_label: nodename
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-web-config
  namespace: monitoring
data:
  web-config.yaml: |
    tls_server_config:
      cert_file: /etc/prometheus/tls/tls.crt
      key_file: /etc/prometheus/tls/tls.key
